### ISSUE TITLE
'Article List' doesn't follow application theme

### ISSUE THREAD

**Issue by RandomUsername404** [flathub/com.gitlab.newsflash#2]
I don't know if this is intended behavior, but it looks weird to me.
![NewsFlash_ArticleList](https://user-images.githubusercontent.com/18629430/90992223-91b74a00-e5ae-11ea-9524-51fb4064bcd5.png)

The same goes for the Article View. When no article is selected and dark mode is enabled, the article area remains white.
![NewsFlash_ArticleView](https://user-images.githubusercontent.com/18629430/90992225-98de5800-e5ae-11ea-9cd0-0a5cac74553d.png)

**Comment by jangernert** [comment]
I have no clue what you mean by "application theme".

**Comment by RandomUsername404** [comment]
I'm talking about dark mode:
![NewsFlash_DarkTheme](https://user-images.githubusercontent.com/18629430/91039590-1d5fc380-e60d-11ea-951d-20d624f561bd.png)

It's selected, but the Article List remains white when I assumed it would follow the selected option. So basically, as is, selecting 'Dark Mode' only makes the left column darker.
![darker_black](https://user-images.githubusercontent.com/18629430/91040480-9f042100-e60e-11ea-8c62-d332d463aa1b.png)

**Comment by jangernert** [comment]
In that case your theme probably doesn't have a dark variant. Just use the default adwaita Gnome theme.
https://stopthemingmy.app/
