### ISSUE TITLE
Newsflash doesn't remember windows state

### ISSUE THREAD

**Issue by Froggy232** [flathub/com.gitlab.newsflash#23]
Hi,
I just installed Newsflash on a freshly installed fedora silverblue.
I installed newsflash through flatpak and flathub.
The problem is the app doesn't remember the windows state : if I launch it then maximize it, then close it, it doesn't remember the state and start windowed when I launch it again.
I am the only one with this problem?
I can provide a video if it's not clear.
Thanks you

**Comment by jangernert** [comment]
Its not implemented. But there is a way to achieve what you are looking for:
> Set the application to keep running in the background: the GUI will appear even quicker and is exactly like you left it. If you don't like it to fetch feeds automatically in the background (either at all or on metered connections) you can turn that off.

https://gitlab.com/news-flash/news_flash_gtk/-/issues/415
