### ISSUE TITLE
[Feature Request] Ability to set a different font for each category/feed

### ISSUE THREAD

**Issue by ArcticDev78** [flathub/com.gitlab.newsflash#26]
Would it be possible to implement a feature that allows us to customize the font for each Category or Feed?

Let's say I have two Categories: **News** and **Entertainment**. To make it better to read news articles, I want to use a font called “Georgia” for the feeds in the **News** Category. And for the feeds in the **Entertainment** Category, I'd like to set a more casual font, such as “Cantarell” for example.

Could this be implemented? Thank you.

**Comment by jangernert** [comment]
No! NewsFlash is not supposed to have every feature under the sun.

> NewsFlash will be an opinionated project right from the start. With FeedReader I gave in to too many feature requests and added too many settings and dconf tweaks over time. This made maintaining and testing a lot harder than necessary.

https://blogs.gnome.org/jangernert/2020/04/05/newsflash/
