### ISSUE TITLE
Ability to configure the site/domain which is pinged to check if online connectivity is working

### ISSUE THREAD

**Issue by ArcticDev78** [flathub/com.gitlab.newsflash#27]
Hi, I am currently experiencing an issue with Newsflash after installing the [Portmaster](https://github.com/safing/portmaster) firewall software. When I open the Newsflash application while the Portmaster firewall is running, the firewall seems to block the “example.com” network traffic that goes through “System DNS”. The following screenshot shows the info:

![Screenshot from 2024-06-12 06-32-04](https://github.com/flathub/com.gitlab.newsflash/assets/131583057/097dd46c-2dee-4b90-9152-02bb21d27266)

I've been trying everything that can be done to allow this network traffic, but it simply does not seem to work. A possible solution would be to allow the user to be able to configure a custom site or domain which will be pinged to check if the online connectivity is working.
Thank you.

**Comment by jangernert** [comment]
`~/.var/app/io.gitlab.news_flash.NewsFlash/config/news-flash/newsflash_gtk.json`

```
"advanced": {
    "proxy": [],
    "accept_invalid_certs": false,
    "accept_invalid_hostnames": false,
    "inspect_article_view": true,
    "article_view_load_images": true,
    "ping_url": "http://example.com/"
  },
```

**Comment by ArcticDev78** [comment]
> `~/.var/app/io.gitlab.news_flash.NewsFlash/config/news-flash/newsflash_gtk.json`
> 
> ```
> "advanced": {
>     "proxy": [],
>     "accept_invalid_certs": false,
>     "accept_invalid_hostnames": false,
>     "inspect_article_view": true,
>     "article_view_load_images": true,
>     "ping_url": "http://example.com/"
>   },
> ```

Thank you so much, I got it to work now!

**Comment by ArcticDev78** [comment]
> `~/.var/app/io.gitlab.news_flash.NewsFlash/config/news-flash/newsflash_gtk.json`
> 
> ```
> "advanced": {
>     "proxy": [],
>     "accept_invalid_certs": false,
>     "accept_invalid_hostnames": false,
>     "inspect_article_view": true,
>     "article_view_load_images": true,
>     "ping_url": "http://example.com/"
>   },
> ```

Thanks a lot, I modified the `ping_url` and it works now! :tada:
