### ISSUE TITLE
Data lost while upgrade 1.1.1 to 1.2.0

### ISSUE THREAD

**Issue by sheesupport** [flathub/com.gitlab.newsflash#6]
Unfortunately I lost all my "starred" and older news articles of my feeds after upgrading from 1.1.1 to 1.2.0 (flatpak update). It would be beneficially when this could be avoided in future upgrades (minor updates does not behaved like that).

**Comment by jangernert** [comment]
I'm terribly sorry. That is indeed a major error on my side. I simply forgot to copy the article data over to the new table during schema migration. I'm not sure how that went unnoticed.
A fix has been commited: https://gitlab.com/news-flash/news_flash/-/commit/5deb029bad03510e1205e1fc8e8618a4c446afab
And I'm working on pushing out a hotfix this evening.

**Comment by jangernert** [comment]
update is out
Let's hope some people will skip the 1.2.0 update.
