### ISSUE TITLE
Keep Articles for One Week reverts to Keep Articles Forever

### ISSUE THREAD

**Issue by mochiballs** [flathub/com.gitlab.newsflash#7]
System: Linux Mint 19.3 Cinnaon
When you go to Settings > App > User Data > Keep Articles and set "Keep Articles" to "One week" it reverts back to "Forever" as soon as you close the Settings window and reopen Settings, or restart News Flash

![keep-article-for-one-week](https://user-images.githubusercontent.com/71861263/106855720-68d1cf80-668b-11eb-852c-fc499fe37b9d.png)

**Comment by jangernert** [comment]
You should look at `$HOME/.var/app/com.gitlab.newsflash/config/newsflash.json` and look if `"keep_articles_days"` is set when you change the setting


![Screenshot from 2021-02-04 08-33-53](https://user-images.githubusercontent.com/12012494/106859882-f5987f80-66c3-11eb-964f-ee343ebff4f0.png)

**Comment by jangernert** [comment]
There was a typo in the conversion of the "week" setting.

https://gitlab.com/news-flash/news_flash_gtk/-/commit/bd2585c0b6590eba143d8c0f332ff4f8126f6099

**Comment by mochiballs** [comment]
Thanks :)
